name: Build for Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build for Linux x86_64
        run: cargo build --release --package echo_test

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: echo_test-linux-x86_64
          path: target/release/echo_test
